In [ ]:
# pip install pandas 
# pip install pip --upgrade

In [1]:
import pandas as pd
import numpy as np

In [2]:
# pip install bs4
# from bs4 import BeautifulSoup

In [3]:
import datetime as dt    

today = pd.to_datetime('today').normalize()

In [4]:
today

Timestamp('2022-05-09 00:00:00')

In [5]:
# pip install instaloader

In [6]:
import requests
import re
from instaloader import Instaloader, Profile

In [7]:
import os
working_directory = os.getcwd()
print(working_directory)

/Users/karakemp

In [8]:
path = working_directory + '/bluejaysdata/IG_Audience.csv'

In [9]:
# 1. Loading in the data
# Reading the data from the csv
data = pd.read_csv(path)
# Getting the profile urls
urls = data['Profile URL']

In [10]:
data.head()

,Date,Blue Jays Player,Profile URL,Follower Count,Position
0,"April 25, 2022",Bo Bichette,boflows1,0,Short Stop
1,"April 25, 2022",Trevor Richards,trevrchrds1,0,Pitcher
2,"April 25, 2022",Toronto Blue Jays Account,bluejays1,0,Blue Jays Account
3,"April 25, 2022",Julian Merryweather,jerryweatherr1,0,Pitcher
4,"April 25, 2022",Tyler Heineman,theineman131,0,Catcher

In [11]:
# Stackoverflow link to this notebook
# https://stackoverflow.com/questions/63348325/how-can-i-quickly-get-the-follower-count-for-a-large-list-of-instagram-users

def getFollowerCount(PROFILE):
    # using the instaloader module to get follower counts from this programmer
    # https://stackoverflow.com/questions/52225334/webscraping-instagram-follower-count-beautifulsoup
    try:
        L = Instaloader()
        profile = Profile.from_username(L.context, PROFILE)
        print(PROFILE, 'has', profile.followers, 'followers')
        return(profile.followers)
    except Exception as exception :
        print(exception, False)
        return(0)

# Follower count List
followerCounts = []
# This loop will fetch the follower count for each user
for url in urls:
    # Getting the profile username from the URL by removing the instagram.com
    # portion and the backslash at the end of the url
    url_dirty = url.replace('https://www.instagram.com/', '')
    url_clean = url_dirty[:-1]
    followerCounts.append(getFollowerCount(url_clean))

# Converting the list to a series, adding it to the dataframe, and writing it to
# a csv
data['Follower Count'] = pd.Series(followerCounts)
data.to_csv('IG_Audience1.csv')

boflows has 296769 followers
trevrchrds has 4224 followers
bluejays has 1453878 followers
jerryweatherr has 3732 followers
theineman13 has 7504 followers
b_zimmer5 has 28033 followers
yuseik18 has 26869 followers
georgespringer has 107959 followers
yimigarcia106 has 11707 followers
a_cimber has 12418 followers
ryan_borucki has 17848 followers
gabriel__mo13 has 10716 followers
hyunjinryu325 has 189240 followers
alexkirk5 has 26410 followers
stgo1313 has 20207 followers
ross_stripling has 89679 followers
cb_2_3 has 61107 followers
zack_collins_ has 21348 followers
kevingausman34 has 29120 followers
matthewchapman26 has 51636 followers
d_jansen31 has 32393 followers
jolamakina has 153318 followers
yunitogurriel has 133238 followers
elchino242 has 73710 followers
alek_manoah6 has 51535 followers
vladdyjr27 has 1095328 followers
raimeltapia has 18009 followers
bowdenfrancis33 has 6151 followers
npearson24 has 30860 followers
saucey07 has 3373 followers
trentthornton has 3231 followers

In [13]:
data['Date'] = today
# data.to_csv('IG_Audience1.csv')

In [14]:
data.head()

,Date,Blue Jays Player,Profile URL,Follower Count,Position
0,2022-05-09,Bo Bichette,boflows1,296769,Short Stop
1,2022-05-09,Trevor Richards,trevrchrds1,4224,Pitcher
2,2022-05-09,Toronto Blue Jays Account,bluejays1,1453878,Blue Jays Account
3,2022-05-09,Julian Merryweather,jerryweatherr1,3732,Pitcher
4,2022-05-09,Tyler Heineman,theineman131,7504,Catcher

In [15]:
data.dropna(how='all', axis=1, inplace=True)

In [16]:
data.head()

,Date,Blue Jays Player,Profile URL,Follower Count,Position
0,2022-05-09,Bo Bichette,boflows1,296769,Short Stop
1,2022-05-09,Trevor Richards,trevrchrds1,4224,Pitcher
2,2022-05-09,Toronto Blue Jays Account,bluejays1,1453878,Blue Jays Account
3,2022-05-09,Julian Merryweather,jerryweatherr1,3732,Pitcher
4,2022-05-09,Tyler Heineman,theineman131,7504,Catcher

In [17]:
path = working_directory + '/bluejaysdata/IG_Audience1.csv'
# 1. Loading in the data
# Reading the data from the csv
data1 = pd.read_csv(path)

In [18]:
data1.head()

,Date,Blue Jays Player,Profile URL,Follower Count,Position
0,2022-05-02 00:00:00,Bo Bichette,boflows1,295332,Short Stop
1,2022-05-02 00:00:00,Trevor Richards,trevrchrds1,4213,Pitcher
2,2022-05-02 00:00:00,Toronto Blue Jays Account,bluejays1,1449465,Blue Jays Account
3,2022-05-02 00:00:00,Julian Merryweather,jerryweatherr1,3726,Pitcher
4,2022-05-02 00:00:00,Tyler Heineman,theineman131,7480,Catcher

In [19]:
finaldata = pd.concat([data, data1])
finaldata

,Date,Blue Jays Player,Profile URL,Follower Count,Position
0,2022-05-09 00:00:00,Bo Bichette,boflows1,296769,Short Stop
1,2022-05-09 00:00:00,Trevor Richards,trevrchrds1,4224,Pitcher
2,2022-05-09 00:00:00,Toronto Blue Jays Account,bluejays1,1453878,Blue Jays Account
3,2022-05-09 00:00:00,Julian Merryweather,jerryweatherr1,3732,Pitcher
4,2022-05-09 00:00:00,Tyler Heineman,theineman131,7504,Catcher
...,...,...,...,...,...
91,2022-04-29,Ramiel Tapia,raimeltapia1,18062,Outfielder
92,2022-04-29,Bowden Francis,bowdenfrancis331,6159,Pitcher
93,2022-04-29,Nate Pearson,npearson241,30824,Pitcher
94,2022-04-29,Tayler Saucedo,saucey071,3393,Pitcher
95,2022-04-29,Trent Thornton,trentthornton1,3230,Pitcher

In [22]:
finaldata['Date'] =  pd.to_datetime(finaldata['Date'])

In [23]:
finaldata.dtypes

Date                datetime64[ns]
Blue Jays Player            object
Profile URL                 object
Follower Count               int64
Position                    object
dtype: object

In [24]:
finaldata.head()

,Date,Blue Jays Player,Profile URL,Follower Count,Position
0,2022-05-09,Bo Bichette,boflows1,296769,Short Stop
1,2022-05-09,Trevor Richards,trevrchrds1,4224,Pitcher
2,2022-05-09,Toronto Blue Jays Account,bluejays1,1453878,Blue Jays Account
3,2022-05-09,Julian Merryweather,jerryweatherr1,3732,Pitcher
4,2022-05-09,Tyler Heineman,theineman131,7504,Catcher

In [25]:
finaldata.reset_index(drop=True, inplace=True)

In [26]:
finaldata.head()

,Date,Blue Jays Player,Profile URL,Follower Count,Position
0,2022-05-09,Bo Bichette,boflows1,296769,Short Stop
1,2022-05-09,Trevor Richards,trevrchrds1,4224,Pitcher
2,2022-05-09,Toronto Blue Jays Account,bluejays1,1453878,Blue Jays Account
3,2022-05-09,Julian Merryweather,jerryweatherr1,3732,Pitcher
4,2022-05-09,Tyler Heineman,theineman131,7504,Catcher

In [27]:
import os
working_directory = os.getcwd()
print(working_directory)

/Users/karakemp

In [28]:
#https://towardsdatascience.com/how-to-export-pandas-dataframe-to-csv-2038e43d9c03 export dataframe to working directory

finaldata.to_csv('IG_Audience1.csv', index_label=None, header=False) # relative position

In [29]:
finaldata.to_csv('IG_Audience1.csv', index=False) # relative position
finaldata.to_csv(working_directory + '/bluejaysdata/IG_Audience1.csv')